---
{{- if and .Values.receive.enabled .Values.receive.ingress.remotewrite.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "thanos.componentname" (list $ "receive") }}-write
  labels:
    app.kubernetes.io/name: {{ include "thanos.name" . }}
    helm.sh/chart: {{ include "thanos.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | replace "+" "_" }}
    app.kubernetes.io/component: receive
    {{- if .Values.receive.ingress.remotewrite.labels }}
  {{ toYaml .Values.receive.ingress.remotewrite.labels | indent 4 }}
    {{- end }}
    {{- with .Values.receive.ingress.remotewrite.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.receive.ingress.remotewrite.defaultBackend }}
  backend:
    serviceName: {{ include "thanos.componentname" (list $ "receive") }}
    servicePort: {{ $.Values.receive.service.remotewrite.port }}
  {{- end }}
  {{- if .Values.receive.ingress.remotewrite.tls }}
  tls:
    {{- range .Values.receive.ingress.remotewrite.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      {{- if .secretName }}
      secretName: {{ .secretName }}
      {{- end}}
    {{- end }}
  {{- end }}
  rules:
  {{- range .Values.receive.ingress.remotewrite.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: {{ $.Values.receive.ingress.remotewrite.path }}
            backend:
              serviceName: {{ include "thanos.componentname" (list $ "receive") }}
              servicePort: {{ $.Values.receive.service.remotewrite.port }}
  {{- end }}
{{- end }}

{{- if and .Values.receive.enabled .Values.receive.ingress.grpc.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "thanos.componentname" (list $ "receive") }}-grpc
  labels:
    app.kubernetes.io/name: {{ include "thanos.name" . }}
    helm.sh/chart: {{ include "thanos.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | replace "+" "_" }}
    app.kubernetes.io/component: receive
    {{- if .Values.receive.ingress.grpc.labels }}
  {{ toYaml .Values.receive.ingress.grpc.labels | indent 4 }}
    {{- end }}
    {{- with .Values.receive.ingress.grpc.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.receive.ingress.grpc.defaultBackend }}
  backend:
    serviceName: {{ include "thanos.componentname" (list $ "receive") }}
    servicePort: {{ $.Values.receive.service.grpc.port }}
  {{- end }}
  {{- if .Values.receive.ingress.grpc.tls }}
  tls:
    {{- range .Values.receive.ingress.grpc.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      {{- if .secretName }}
      secretName: {{ .secretName }}
      {{- end}}
    {{- end }}
  {{- end }}
  rules:
  {{- range .Values.receive.ingress.grpc.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: {{ $.Values.receive.ingress.grpc.path }}
            backend:
              serviceName: {{ include "thanos.componentname" (list $ "receive") }}
              servicePort: {{ $.Values.receive.service.grpc.port }}
  {{- end }}
{{- end }}
