{{- if .Values.receive.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "thanos.componentname" (list $ "receive") }}
  {{- with .Values.receive.service.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
  labels:
    app.kubernetes.io/name: {{ include "thanos.name" . }}
    helm.sh/chart: {{ include "thanos.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ $.Chart.AppVersion | replace "+" "_" }}
    app.kubernetes.io/component: receive
{{ with .Values.receive.service.labels }}{{ toYaml . | indent 4 }}{{ end }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.receive.service.grpc.port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
    - port: {{ .Values.receive.service.http.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.receive.service.remotewrite.port }}
      targetPort: remotewrite
      protocol: TCP
      name: remotewrite
  selector:
    app.kubernetes.io/name: {{ include "thanos.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: receive
{{ with .Values.receive.service.matchLabels }}{{ toYaml . | indent 4 }}{{ end }}
{{ end }}